### ISSUE TITLE
Thoughts on Jitsi Meet?

### ISSUE THREAD

**Issue by n2liquid** [jeremija/peer-calls#44]
Hi folks. Just wanted to know if you know about Jitsi Meet and what your thoughts are on it. Peer Calls is really cool, but Jitsi Meet seems to do the same things and looks a lot more mature.

(Sorry I couldn't find a better place to ask you this.)

Thanks!

**Comment by jeremija** [comment]
Hi @n2liquid - I do not have any comments on Jitsi Meet since I've never used it, but I see that it is an Atlassian product. Atlassian is a big company that had a [revenue][atl] of over 600 million dollars last year, whereas I wrote most of the Peer Calls code myself in my free time, so I'm not surprised if Jitsi Meet has more features 🙂

I currently do not have the time to build in new features into Peer Calls, but anybody is welcome to create a pull request with a new feature, and I'll make sure to review it and give feedback.

[atl]: https://en.wikipedia.org/wiki/Atlassian

**Comment by n2liquid** [comment]
Yes, I like Peer Calls. Jitsi Meet is probably on the road to feature bloat. I don't know why it gets so many releases when it looks like such a simple, stable app. Peer Calls wins on that aspect, it looks like it just needs a slicker UI. I also feel like Jitsi Meet's dial-in feature is just inherently unsafe and shouldn't be there (unless it could be made safe), but I could be wrong...

Something like Peer Calls / Jitsi Meet is something I've wanted to build since 2013, but was never a priority, so I never even tried. When I get to it, I'll certainly have a look at this project and maybe contribute.

Anyways, just wanted to know what your thoughts were. If you ever give Jitsi Meet a closer look and has any comments, and you still remember me, please let me know :smiley: Thanks!

**Comment by jeremija** [comment]
Thanks for your comments! One thing I've been meaning to add is file sharing. I've also been trying to keep the server-side as simple as possible so I do not need to run a database. But more advanced features would require user accounts support, and that would require adding a database.

I definitely agree that PeerCalls UI could be revamped 🙂

**Comment by lil5** [comment]
> Thanks for your comments! One thing I've been meaning to add is file sharing. I've also been trying to keep the server-side as simple as possible so I do not need to run a database. But more advanced features would require user accounts support, and that would require adding a database.

https://file.pizza/ ([npm](https://www.npmjs.com/package/filepizza) pakage, [github](https://github.com/kern/filepizza) repo) is perfect for that. I'd prefer that it wouldn't be added and keep the unix philosophy.
