### ISSUE TITLE
Stream from Source to Map

### ISSUE THREAD

**Issue by excelwebzone** [jeremija/peer-calls#52]
Add the ability to stream geolocation data for any of sources (participants), process them, and display it in a map.

**Comment by excelwebzone** [comment]
@jeremija I have 2 options I thought we can go with:
1. Just adding a simple icon on the chat that will post a map image (with link to Google Maps)
2. Add **map** link toggle on the chat (header) that will show shared location of all participants

> See example: https://github.com/joycecyoj/ShareLocation

**Comment by excelwebzone** [comment]
Here is another simple example I found:

## Server

```js
const locationMap = new Map()

io.on('connection', (socket) => {
  socket.on('location:update', (pos) => {
    locationMap.set(socket.id, pos)
    socket.emit('location:update', Array.from(locationMap))
  })

  socket.on('disconnect', () => {
    socket.emit('client:disconnect', socket.id)
    locationMap.delete(socket.id)
  })
})
```

## Client

```js
  let map
  let markers = new Map()
  const socket = io('/')
  const initialZoom = 9
  const positionOptions = { enableHighAccuracy: true, maximumAge: 0 }

  // Initialize Google map on user's current location.
  function initMap() {
    navigator.geolocation.getCurrentPosition((pos) => {
      const { latitude: lat, longitude: lng } = pos.coords
      map = new google.maps.Map(document.getElementById('map'), {
        center: { lat, lng },
        zoom: initialZoom
      })
    })
  }

  // Poll for user's current location every 2 seconds
  setInterval(() => {
    navigator.geolocation.getCurrentPosition((pos) => {
      const { latitude: lat, longitude: lng } = pos.coords
      socket.emit('location:update', { lat, lng })
    }, (err) => {
      console.log(err)
    }, positionOptions)
  }, 2000)

  // Set markers
  socket.on('location:update', (locations) => {

    if (locations.length > 0) {
      markers.forEach((marker, id) => {
        marker.setMap(null)
        markers.delete(id)
      })
    }

    locations.forEach(([id, position]) => {
      if (position.lat && position.lng) {
        const marker = new google.maps.Marker({
          map,
          position,
          title: id,
        })
        markers.set(id, marker)
      }
    })
  })

  socket.on('client:disconnect', id => markers.delete(id))
```

**Comment by jeremija** [comment]
Hi @excelwebzone,

I believe [`geolocation.watchPosition`][geo] can be used instead of polling for location every two seconds.

Since the Google Maps API is purely a presentational layer, I would try to separate the concerns. Rather than creating the google map in the position handler, I'd keep the coordinates in the redux state, and create a React component that renders the map. This way we could swap out different map providers as necessary. There are already [components][react-maps] for this.

Most (if not all) map providers start charging after a certain API usage threshold is reached <sup>[#1][1], [#2][2], [#3][3]</sup>. As an alternative, we could use something simpler like [datamaps][datamaps] or [react-simple-maps][react-simple-maps]. While these libraries do not provide the same level of details, they do not depend on 3rd-pary servers or services.

[geo]: https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/watchPosition
[react-maps]: https://www.npmjs.com/search?q=react%20map
[1]: https://cloud.google.com/maps-platform/pricing/sheet
[2]: https://www.mapbox.com/pricing/
[3]: https://operations.osmfoundation.org/policies/tiles/
[datamaps]: http://datamaps.github.io/
[react-simple-maps]: https://www.npmjs.com/package/react-simple-maps

Hope this helps,
jeremija

**Comment by excelwebzone** [comment]
@jeremija I have started implementing this feature.. check https://github.com/excelwebzone/peer-calls/tree/map. I'd get an error when running application:

```
0 err>
0 err>/Users/michael.arieli/Sites/peer-calls/node_modules/react-native-maps/index.js:1
0 err>import MapView, { Animated, MAP_TYPES, ProviderPropType } from './lib/components/MapView';
0 err>^
0 err>ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

Can you see if you can figure it out before I create a PR.. Thanks.

**Comment by excelwebzone** [comment]
Based on this article: https://www.scaledrone.com/blog/react-native-maps-tutorial-find-my-friends/

**Comment by excelwebzone** [comment]
If we replace the `react-native` with `react-native-web` it will allows us to keep using **`ReactDOM`**, but we still need to figure the map piece.. please let me know. Thanks.
