### ISSUE TITLE
Question Regarding Performance

### ISSUE THREAD

**Issue by mdemarco1234** [jeremija/peer-calls#62]
How many users will the server application handle before performance degradation occurs? Does there ever need to be a load balancing solution in high volume use cases? What is the recommended hardware and software topology for high volume use cases? Additionally any recommended internet speeds to optimize performance and camera resolution metrics?

**Comment by mdemarco1234** [comment]
let me focus the last statement. What is the recommended camera resolution for an optimal visual experience?

**Comment by jeremija** [comment]
Hi @mdemarco1234, apologies for replying this late to your questions. The bandwidth and processor usage depend on the resolution and the codec used. Another way to improve performance would be to try limit the bandwidth in SDP like suggested in #82, however I believe the browsers should adjust this automatically depending on network status.

Right now the peers establish a mesh network and each peer sends video to all other peers in room. Because of this, it quickly becomes expensive to stream to 4+ users.

As mentioned in #37, #82 and some other issues, the best solution would be to implement an SFU and this is on my roadmap for version v4, and I've already started working on it.

I'm going to close this issue in favor of the other two mentioned, but please feel free to ask any questions over there or report any bugs you might come across.

**Comment by subhendukundu** [comment]
Now that we are V4, SFU is implemented, did we do a performance test?
So that number would excite people.
For example how many users did we try with number of core machines etc and how much was the utilization on the video quality?
If we haven't done any, I would love to contribute to this one.

**Comment by jeremija** [comment]
@subhendukundu yeah that's on my TODO list but I can't seem to find the time.

There's https://github.com/pion/ion-load-tool and perhaps it can be modified to put a load on Peer Calls.

In the current version of Peer Calls is that every peer will subscribe to every other peer. Perhaps this can be made in a better way, for example to only request the video of active stream. Once multicast support is finished in Pion, a lot of other interesting stuff will be possible.

But first I'll focus on making Peer Calls SFU distributed, and implementing insertable streams to provide end to end encryption for SFU.

**Comment by subhendukundu** [comment]
So how many do support at the moment in one room? Did you ever find out that?
So I was thinking to work on end to end encryption for SFU with Pion ion, as I see its not gonna be that difficult to do.
Curious how different peer-calls over pion/ion? I saw under the hood they use nats-server.
