### ISSUE TITLE
Only Chrome to Chrome or Firefox to Firefox is feasible

### ISSUE THREAD

**Issue by jimver04** [jeremija/peer-calls#65]
Firefox Laptop to Chrome Mobile is not feasible
I managed to connect between: 
- Chrome at laptop and Chrome at mobile
- Chrome mobile and Chrome Mobile
- Firefox  Laptop and Firefox  mobile.

Server: Ubuntu 16.04
Laptop: Windows 10, Chrome 77, Firefox 69
Android 9: Chrome 76, Firefox 68

Best,
D.

**Comment by jeremija** [comment]
Thanks for reporting and sorry for replying this late - I must've missed this message. I believe the problem was because the ICE server entriy on peercalls.com was configured using the `turns:` prefix, which caused connectivity issues in Firefox. Now it's configured to use `turn:` and based on my tests the latest version should work across all major browsers (Chrome, Firefox, Safari, Edge). Please reopen this issue if you continue to experience connectivity issues on peercalls.com.
