### ISSUE TITLE
Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by sah-anshu** [jeremija/peer-calls#67]
Hi,

When i run with localhost:3000 it works properly. 
But when i Open on LAN IP to access the application on another PC.

BIND=192.168.1.4 npm start

[PeerCalls]04/12/2019, 20:12:22
Error: TypeError: Cannot read property 'call' of undefined

--
node v13.2.0
npm 6.13.1

Thanks in advance.

**Comment by jeremija** [comment]
Hi @sah-anshu,

Thank you for reporting this. Could you post the stack trace too? I suspect this is because you are not using HTTPS and browsers will [block access to microphone and camera][cam].

You can try to enable HTTPS by using the pregenerated self-signed certificates for localhost (in config folder, see README), but then you would need to add an exception for the site in your browser.

[cam]: https://stackoverflow.com/questions/34197653/getusermedia-in-chrome-47-without-using-https

**Comment by phuongnguyen2511** [comment]
Hello, You can help me with the problem: when I'm alone, I can still send messages and save them. People who connect later can review.
Thanks

**Comment by jeremija** [comment]
@phuongnguyen2511 I'm sorry but I do not understand your question. Please clarify?
