### ISSUE TITLE
second test

### ISSUE THREAD

**Issue by StephanKrauss** [jeremija/peer-calls#73]
Hello,

now i have a simple server.
This server runs on Ubuntu 18.0.4 .
I have installed the docker container with
docker run -d --rm -it -p 3000:3000 jeremija/peer-calls:3.0.8

The server IP is:    **redacted**

I get a error when i press the 'Join Call' Button.

-----
Error: TypeError: t is undefined
TypeError: t is undefined
-----

do you have any idea ?

Sincerely, Stephan

**Comment by StephanKrauss** [comment]
Ups, there is a second error.

When i press the 'Start Session' Button

-----
Connected users: 1
Ready for connections
Connected to server socket
TypeError: navigator.mediaDevices is undefined
-----

I use Firefox 73.0.1 , 64 Bit, Linux Mint

Greetings

Stephan

**Comment by jeremija** [comment]
Hi Stephan, I'll send you an email shortly so we can take this discussion off github.

**Comment by pragmatech** [comment]
Fwiw, I recently got the app (3.0.17) to work remarkebly well on ubuntu 18.04 on a small Google vm. Whereas, my fiddling with the added layer of Docker had been less successful. I happen to find Yarn to seemingly work better with node apps in this configuration as well. And tangential to this github reporting (which I don't really use) or otherwise, I'm finding the chat component to not function in both directions at times, and a general 'dropping' of things (vid going black, or screenshare, etc.). Significantly, the audio is rock solid. Even seems like duplex audio which is great. I'd be happy to drop into a 'room' on the app peercalls.com should anyone care to discuss, etc. 
ps- I assume the dropping behavior is coming from socket.io's magic but pragmatic way to switch from polling to websockets and so on. (Some other signaling servers using socket.io don't seem to do the connect/reconnect and I'd love to find how that works too. I digress again.)Still, for myself, this limitation starts to be preferrable to: how configuring nginx to websockets and scalability can just be a frustration. Here, Jerko has somehow gotten Redis onboard and with the ssr that seems to barely consume at my server at all. Anyway, as a hacky but persistent student of the ecosystem of webrtc, and as a fan of the composability of react, nonetheless, I've found that a frontend on Netlify to have more weirdness than just a node app. Thanks a bunch and sorry for the ramble-factor!
Darren
