### ISSUE TITLE
stream image download

### ISSUE THREAD

**Issue by ahmetozalp** [jeremija/peer-calls#79]
Hello,

How can I download the image of the camera image? Whichever video is clicked on and download a screenshot

**Comment by jeremija** [comment]
Unfortunately this is not possible at the moment. As a workaround you could take a screenshot.

**Comment by ahmetozalp** [comment]
I solved the problem with canvas, now I can take a screenshot

**Comment by jeremija** [comment]
Did you mean to allow the users to take a screenshot, or take a screenshot for app purposes?

At some point, someone added a feature to screenshot of user images as avatars, but I had to [comment it out](https://github.com/jeremija/peer-calls/blob/master/src/client/components/Input.tsx#L61-L72) during refactoring because the code became very convoluted.

On the other hand, taking a screenshot in Firefox is really simple - right click on video and click `Save Snapshot As...`

<img width="369" alt="image" src="https://user-images.githubusercontent.com/1489493/78222332-5ca64000-74c5-11ea-8daa-cf796c743f3f.png">

**Comment by ahmetozalp** [comment]
I used this system (no right click on mobile phones) because it uses it in different browsers, I wrote a code similar to the code put on the comment line
