### ISSUE TITLE
Stream permission issues 

### ISSUE THREAD

**Issue by litashg** [jeremija/peer-calls#85]
Hello, @jeremija ! 
I found a few issues: 
1. Option 'Disable Video' in the dropdown - doesn't work
2. Video translation starts before you press 'Join Call' button

**Comment by jeremija** [comment]
> 1. Option 'Disable Video' in the dropdown - doesn't work

Did you disable both Video and Audio? Because Audio-only works for me.

> 2. Video translation starts before you press 'Join Call' button

Correct, this is on my TODO list to fix this week. I'll also add a nickname dialog.

**Comment by litashg** [comment]
1. If I disable both Video and Audio - I got an error in the top console. Audio disable button - works well. Problems are if disable only Video. 

2. Nice. I add faker lib in my dev code to generate Human-like names by default. But I don't know how to push data to your repo. Got permission error.

**Comment by jeremija** [comment]
Correct, the browser can't get the stream because there's nothing to get.

If you wish to contribute please submit a [pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request). But before opening a pull request, please open an issue to check if this is something I can accept - I'm adding a lot of new stuff now and it could collide, and I wouldn't want anybody to do all the hard work with preparing the pull request only to be rejected in the end. Hope you understand!

Also check this guide [CONTRIBUTING.md](https://github.com/jeremija/peer-calls/blob/master/CONTRIBUTING.md)

**Comment by litashg** [comment]
Thank you! That issue was on my side. I found it. 
Have a nice day!

**Comment by jeremija** [comment]
Added nickname prompt in v3.0.20, along with a flexbox-based video wall.
